[project]
name = "ComfyUI-WanAnimatePreprocess"
description = "Wan Animate preprocess in one node: pose, face crops, person mask and pose images, with a guard"
version = "1.0.4"
license = {file = "LICENSE"}
dependencies = ["opencv-python", "onnx"]

[project.urls]
Repository = "https://github.com/0xBeycan/ComfyUI-WanAnimatePreprocess"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kijai"
DisplayName = "ComfyUI-WanAnimatePreprocess"
Icon = ""
